version: '3.3'

services:

  cky97:
    container_name: cky97
    image: cky97/php:8
    restart: unless-stopped
    ports:
      - '8088:80'
      # - '443:443'
    volumes:
      - ../:/var/www       ## local
      - /etc/localtime:/etc/localtime:ro
    networks:
      payIni:
        ipv4_address: 172.21.0.4


networks:
  payIni:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
